spring:
  application:
    name: web-ui

server:
  port: 8080

game-server:
  base-url: http://localhost:8081
  create-game-path: /game

records-storage:
  base-url: http://localhost:8082
  game-records-path: /game-records