server:
  port: 8081

redis:
  host: localhost
  port: 6379
  username:
  password:

websocket:
  client: http://localhost:8080

records-storage:
  base-url: http://localhost:8082
  game-records-path: /game-records